### PR TITLE
Match Angular 1.3 and above

### LINKED ISSUE #694: Support Angular 1.5 for npm and bower
Angular 1.5 is fresh off the press. The [bower](bower) and [npm](npm) installs should support be able to resolve Angular 1.5 as a dependency.

[bower]: https://github.com/firebase/angularfire/blob/master/package.json#L30
[npm]: https://github.com/firebase/angularfire/blob/master/bower.json#L28

### PR DESCRIPTION
**Pull request by davideast**
Closes #694.

cc: @jwngr, @katowulf, @jamestalmage

### CODE REVIEW

**Comment by davideast** [comment]
Sent this too early.

**Comment by davideast** [comment]
e2e's are passing and failing at (what feels like) random, working on the fix.

**Comment by davideast** [comment]
I have this build working locally. Can't figure out what's going on with Travis.

**Comment by katowulf** [comment]
It looks like one of the polyfills we added for AngularFire doesn't work with $$sanitizedUriProvide in the newest Angular versions. : (

**Pull request merged**
