### PR TITLE
Added a line to README.md

### PR DESCRIPTION
**Pull request by wbhob**
So people don't make the same mistake I did!

### CODE REVIEW

**Comment by wbhob** [comment]
I signed it!

**Comment by wbhob** [comment]
I signed it!

On Fri, May 27, 2016 at 9:05 AM, googlebot <notifications@github.com> wrote:

> Thanks for your pull request. It looks like this may be your first
> contribution to a Google open source project. Before we can look at your
> pull request, you'll need to sign a Contributor License Agreement (CLA).
>
> 📝 *Please visit https://cla.developers.google.com/
> <https://cla.developers.google.com/> to sign.*
>
> Once you've signed, please reply here (e.g. I signed it!) and we'll
> verify. Thanks.
> ------------------------------
>
>    - If you've already signed a CLA, it's possible we don't have your
>    GitHub username or you're using a different email address. Check your
>    existing CLA data <https://cla.developers.google.com/clas> and verify
>    that your email is set on your git commits
>    <https://help.github.com/articles/setting-your-email-in-git/>.
>    - If you signed the CLA as a corporation, please let us know the
>    company's name.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/firebase/angularfire/pull/725#issuecomment-222141054>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEPIEiN942Drl2rh5yxQxjQA-nGzwDw0ks5qFuwdgaJpZM4Ioe1I>
> .
>



-- 
Wilson Hobbs
CEO Glasstache
(404) 719-3252
wilsonhobbs1@gmail.com
wilsonhobbs.com

**Comment by wbhob** [comment]
I made one commit @googlebot.

**Comment by jwngr** [comment]
Thanks for the PR, but the branch you forked is the one that is upgrading AngularFire to `2.0.0`, so your change will be out-of-date as soon as that branch gets merged. Also, all the commits included in this PR are not ready and we are tracking this work in #717 .

It's safe to assume that if something is not in `master`, it shouldn't be relied upon yet.

**Pull request closed without merging**
