### PR TITLE
Fixes #649: Run CI against latest stable Node and use new Travis infra

### PR DESCRIPTION
**Pull request by jamestalmage**
@jwngr - you just needed matching version of ngMocks

angular/angular.js#6439

### CODE REVIEW

**Comment by jamestalmage** [comment]
@googlebot you are half right. But I am pretty sure @jwngr is on-board.

**Comment by jamestalmage** [comment]
Whoa. that makes it run a lot faster.

**Comment by jwngr** [comment]
Hey, look at that! Awesome! They definitely do run a lot quicker. I know I had updated my PR to just be against `stable`, but I wonder if we should also still run against at least Node `0.12`. That's what I've been updated our other projects to (example [here](https://github.com/firebase/geofire-js/blob/e1f3c9afb33268779156ab19ff7bdab78060e2d0/.travis.yml#L3-L4)). My main worry is that since the AngularFire tests have historically been flaky (especially the end-to-end tests), we may have a lot more false positives with test failures...

That being said, this is a good change and I'm merging it in! Thanks a lot James!

**Comment by katowulf** [comment]
☃☃☃☃

**Pull request merged**
