### PR TITLE
Fixes to drop-bower PR

### PR DESCRIPTION
**Pull request by jamestalmage**
Same branch as #656, but that was merged and reverted.

The fixes are here.

I updated to `0.12.0` in the blind. I haven't actually run the build against it (it will certainly fail since `0.12.0` isn't in npm yet).

@katowulf - you should be able to re-trigger the travis build once mockfirebase is published to npm.

### CODE REVIEW

**Comment by katowulf** [comment]
I have re'd the trigger'd

**Comment by jamestalmage** [comment]
woot!

**Comment by jwngr** [comment]
Thanks for cleaning this up @jamestalmage! I only have a few comments:
 * I don't think we want any `.txt` files in there. The `changelog.txt` is just used for our release tool and does not actually contain anything useful for people.
 * None of the globs catch the `LICENSE` file (note that it doesn't end in `.md`).
 * The fewer files included the better, in my opinion.

I'd suggest this:

```
"ignore": [
  "**/*",
  "!dist/*.js",
  "!README.md",
  "!LICENSE",
  "!index.js"
]
```

I don't intend to be pedantic here. Sorry if it comes across that way. I've been code reviewing a thousand things today so maybe I'm just in a mood to point out issues :hammer:

**Comment by jwngr** [comment]
Just saw your message about `index.js`. I think you're right in that we can drop it. So, I'd go with this:

```
"ignore": [
  "**/*",
  "!LICENSE",
  "!README.md",
  "!dist/*.js"
]
```

**Comment by jamestalmage** [comment]
Back to you!

**Comment by jwngr** [comment]
Looks good! Thanks again James!

@katowulf - Did you intentionally release `0.12.0` of mockfirebase to npm and not to Bower? Looks like [it is missing the `0.12.0` tag](https://github.com/katowulf/mockfirebase/releases).

**Pull request merged**
