### PR TITLE
Updated guides with $firebaseAuth issues #743

### PR DESCRIPTION
**Pull request by matheushf**
Guides updated with fix related to issue  [#743 ](https://github.com/firebase/angularfire/issues/743)

### CODE REVIEW

**Comment by jwngr** [comment]
Thanks for the PR! I think we just want to make sure all the docs are for the newest code, so let's go ahead and just keep the `var auth = $firebaseAuth();` lines in all these and remove the rest. Thanks for catching our mistake!

**Comment by jwngr** [comment]
You missed one last one in `docs/quickstart.md` that needs to be slimmed one.

**Comment by matheushf** [comment]
Oh sorry! I forgot that last one

**Comment by jwngr** [comment]
Looks good. Thanks for the PR and helping us improve our docs!

**Pull request merged**
