### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by niieq**
### Description

Typo in documentation

### CODE REVIEW

**Comment by jwngr** [comment]
Thanks for fixing that typo. You need to sign the CLA as noted above and respond with "I signed it!" and then I'll be able to merge this change in.

**Comment by jwngr** [comment]
Closing in favor of #873 since the CLA was never signed. Thank you for pointing this out though!

**Comment by niieq** [comment]
Hi,

I signed it!

**Comment by niieq** [comment]
Hi,

I signed the CLA. I sent you an email to tell you I have done it.

Thanks,

**Comment by jwngr** [comment]
#873 has already been merged in so the docs have been updated already. Thank you again!

**Pull request closed without merging**
