### PR TITLE
Adding firebase 3.x authentication methods

### PR DESCRIPTION
**Pull request by idanen**
### Description

Adding the ability to link a user to a new user with email and password.

### Code sample

```js
angular.module('some-module', ['firebase'])
  .controller('MyCtrl', function MyCtrl($fireabseAuth) {
    this.authObj = $firebaseAuth();
    // ... Assuming user logged in somehow. Anonymously, or with other credentials
    this.user = this.authObj.$getAuth();

    // ... other logic ...

    // This could be linked to some `ng-click` for example
    this.linkUser = function (email, password) {
        this.authObj.$linkUser(email, password)
            .then(function (authData) {
                // This will not trigger a `$digest`, so do so if needed using `$timeout`, `$scope.$apply` or whatever suits you.
                this.user = authData;
            }.bind(this));
    };

    // Another way to get the user: listening to `$onAuthStateChanged`
    this.authObj.$onAuthStateChanged(function(firebaseUser) {
      if (firebaseUser) {
        console.log("Signed in as:", firebaseUser.uid);
        this.user = firebaseUser;
      } else {
        console.log("Signed out");
        this.user = undefined;
      }
    });
  });
```

Add the `$linkUser` method. #764

### CODE REVIEW

**Comment by RWOverdijk** [comment]
Can we just all agree that CLAs and weird licenses suck?

What's the status on this?

**Comment by idanen** [comment]
Looked at the commit I pushed back then. Turns out I had my git config with my work email which I no longer have access to 🙁
I'll try to merge the same commit with the correct config

**Comment by RWOverdijk** [comment]
@idanen thank you! :)

**Comment by idanen** [comment]
No luck merging the same commit.

Submitted a new PR with the same change (but more tests 😊).

Take a look at the issue, I think the path to implement isn't decided yet.
The PR is kind of a suggestion, not sure it's the best path.

**Comment by idanen** [comment]
Lost access to the email I made this PR with, so closing... 

Made a new PR #932

**Pull request closed without merging**
