### PR TITLE
Fix unused var randomRoomId

### PR DESCRIPTION
**Pull request by alexsales**
### Code sample

Fix also describes how to create and use a custom key when working with data.

### CODE REVIEW

**Comment by alexsales** [comment]
I'm not sure why "The Travis CI build could not complete due to an error". Is this something I need to fix on my end?

**Comment by jwngr** [comment]
Thanks for the PR.

The `randomRoomId` thing was actually a bit of a hack we put together in our old docs to make sure our live code examples worked properly. We should actually just remove the line defining `randomRoomId` in every file since we don't actually use them anymore in the code samples. Would you mind updating this PR to remove the `randomRoomId` lines from `docs/guide/synchronized-objects.md ` and `docs/guide/introduction-to-angularfire.md `?

> I'm not sure why "The Travis CI build could not complete due to an error". Is this something I need to fix on my end?

This isn't your fault. It's a configuration issue on our end. We can just ignore the failure since this is a docs-only change.

**Comment by alexsales** [comment]
No problem. The changes should now be done for both `docs/guide/synchronized-objects.md` and `docs/guide/introduction-to-angularfire.md`.

**Comment by jwngr** [comment]
Merged. Thanks again!

**Pull request merged**
